Repository AconInc/ACON-Android, pull requests merged in 2025-02, with the labels that each got.

#2 [Init/#1] 1차 스프린트 시작 및 레포 이동
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 🐸성민🐸, INIT

#3 [Fix#1] TargetSdk 변경
  app/build.gradle.kts
Labels: FIX🔨, 🐸성민🐸

#10 [Feat/#7] 프로필 조회 API 연결
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/ProfileRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/di/ApiModule.kt
  data/src/main/kotlin/com/acon/acon/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/profile/ProfileResponse.kt
  data/src/main/kotlin/com/acon/acon/data/remote/ProfileApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/model/profile/Profile.kt
  domain/src/main/java/com/acon/acon/domain/repository/ProfileRepository.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/ProfileViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/composable/ProfileScreen.kt
Labels: FEATURE✨, 🐸성민🐸

#11 [Feat/#8] 로그아웃, 회원탈퇴 API 연동
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SettingsNavigation.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/local/TokenLocalDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/AuthRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/UserRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/di/ApiModule.kt
  data/src/main/kotlin/com/acon/acon/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/acon/acon/data/dto/request/DeleteAccountRequest.kt
  data/src/main/kotlin/com/acon/acon/data/dto/request/LoginRequest.kt
  data/src/main/kotlin/com/acon/acon/data/dto/request/LogoutRequest.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/AreaVerificationResponse.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/LoginResponse.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/RefreshResponse.kt
  data/src/main/kotlin/com/acon/acon/data/remote/AuthApi.kt
  data/src/main/kotlin/com/acon/acon/data/remote/UserApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/AreaVerificationRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/SocialRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/TokenRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/error/user/PostLogoutError.kt
  domain/src/main/java/com/acon/acon/domain/model/area/Area.kt
  domain/src/main/java/com/acon/acon/domain/model/user/RefreshToken.kt
  domain/src/main/java/com/acon/acon/domain/model/user/VerificationStatus.kt
  domain/src/main/java/com/acon/acon/domain/repository/TokenRepository.kt
  domain/src/main/java/com/acon/acon/domain/repository/UserRepository.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/ProfileViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/SettingsViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreenContainer.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/DeleteAccountViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/composable/DeleteAccountScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/composable/DeleteAccountScreenContainer.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/type/DeleteReasonType.kt
  feature/settings/src/main/res/values/strings.xml
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
Labels: FEATURE✨, 🐸성민🐸

#18 [Feat/#9] 로그인 후 동네인증 여부에 따른 분기 처리, AuthAuthenticator 수정
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/dialog/AconOneButtonDialog.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/dialog/PermissionDialog.kt
  core/designsystem/src/main/res/values/strings.xml
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/permission/LocationPermission.kt
  data/src/main/kotlin/com/acon/acon/data/di/AuthAuthenticator.kt
  data/src/main/kotlin/com/acon/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/profile/ProfileResponse.kt
  data/src/main/kotlin/com/acon/acon/data/remote/ProfileApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/SocialRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/repository/SocialRepository.kt
  domain/src/main/java/com/acon/acon/domain/repository/UserRepository.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationScreenContainer.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationState.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationViewModel.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/PreferenceMapScreen.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/component/DottoriSelectionBottomSheet.kt
  feature/areaverification/src/main/res/values/strings.xml
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreenContainer.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/SettingsViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/DeleteAccountViewModel.kt
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreenContainer.kt
  feature/spot/src/main/res/values/strings.xml
Labels: FEATURE✨, 🐸성민🐸

#19 [Feat/#15] presigned url api connect
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/textfield/AconTextField.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/ProfileRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/acon/data/dto/request/updateProfileRequest.kt
  data/src/main/kotlin/com/acon/acon/data/remote/ProfileApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/repository/ProfileRepository.kt
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/BirthdayVisualTransformation.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
  gradle/libs.versions.toml
Labels: ADD➕, FEATURE✨

#21 [Feat/#20] profile mod navigation
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/textfield/AconTextField.kt
  data/src/main/kotlin/com/acon/acon/data/remote/OnboardingApi.kt
  data/src/main/kotlin/com/acon/acon/data/remote/ProfileApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/error/profile/ValidateNicknameError.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/CustomModalBottomSheet.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/ProfilePhotoBox.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/galleryGrid/composable/GalleryGridScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/galleryList/composable/GalleryListScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/BirthdayVisualTransformation.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
Labels: FEATURE✨, 🐇지원🐇

#24 [Feat/#17 인증 동네 UI, 컴포넌트 구현 및 API 연결
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/AreaVerificationNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SettingsNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SignInNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SpotNavigation.kt
  build.gradle.kts
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/dialog/AconTwoButtonDialog.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/snackbar/AconSnackBar.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/snackbar/AconTextSnackBar.kt
  core/designsystem/src/main/res/drawable/ic_area_verificaiton_g_17.xml
  data/src/main/kotlin/com/acon/acon/data/datasource/local/TokenLocalDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/AreaVerificationDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/area/AreaVerificationResponse.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/area/VerifiedAreaListResponse.kt
  data/src/main/kotlin/com/acon/acon/data/remote/AreaVerificationApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/AreaVerificationRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/TokenRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/error/area/DeleteVerifiedAreaError.kt
  domain/src/main/java/com/acon/acon/domain/model/area/Area.kt
  domain/src/main/java/com/acon/acon/domain/repository/AreaVerificationRepository.kt
  domain/src/main/java/com/acon/acon/domain/repository/TokenRepository.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationRoute.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationScreenContainer.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationSideEffect.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationState.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationViewModel.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/PreferenceMapScreen.kt
  feature/areaverification/src/main/res/values/strings.xml
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/VerifiedAreaChip.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreenContainer.kt
  feature/profile/src/main/res/values/strings.xml
  feature/settings/src/main/java/com/acon/acon/feature/SettingsRoute.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/SettingsViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreenContainer.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/type/SettingsType.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/component/AddAreaButton.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/component/VerifiedAreaChip.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/screen/LocalVerificationViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/screen/composable/LocalVerificationScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/screen/composable/LocalVerificationScreenContainer.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/DeleteAccountViewModel.kt
  feature/settings/src/main/res/values/strings.xml
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
Labels: FEATURE✨, FIX🔨, 🐸성민🐸, UI✨

#27 [Feat/#25] 법정동 조회 API
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/SpotRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/TokenRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/dto/response/area/LegalAreaResponse.kt
  data/src/main/kotlin/com/acon/acon/data/remote/SpotApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/AreaVerificationRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/SpotRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UploadRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/error/area/DeleteVerifiedAreaError.kt
  domain/src/main/java/com/acon/acon/domain/error/area/GetLegalDongError.kt
  domain/src/main/java/com/acon/acon/domain/error/area/PostVerifyAreaError.kt
  domain/src/main/java/com/acon/acon/domain/error/spot/FetchSpotListError.kt
  domain/src/main/java/com/acon/acon/domain/error/upload/GetVerifySpotLocationError.kt
  domain/src/main/java/com/acon/acon/domain/error/user/GetSuggestionsError.kt
  domain/src/main/java/com/acon/acon/domain/model/area/LegalArea.kt
  domain/src/main/java/com/acon/acon/domain/repository/SpotRepository.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
Labels: FEATURE✨, 🐸성민🐸

#30 [Feat/#28] 위/경도 서비스 제공 지역 밖일 때 (40405) UI, 다이얼로그 표시
  app/src/main/java/com/acon/acon/navigation/nested/AreaVerificationNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SettingsNavigation.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/dialog/AconOneButtonDialog.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/screen/LocalVerificationViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/screen/composable/LocalVerificationScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/verification/screen/composable/LocalVerificationScreenContainer.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/EmptySpotListView.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/res/values/strings.xml
  feature/upload/build.gradle.kts
  feature/upload/src/main/java/com/acon/acon/feature/upload/UploadContainer.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/UploadState.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/UploadViewModel.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/component/LocationSearchBottomSheet.kt
Labels: FEATURE✨, FIX🔨, 🐸성민🐸, UI✨

#32 [Init/#31] amplitude settings
  .github/workflows/android_build_ci.yml
  app/src/main/java/com/acon/acon/AconApplication.kt
  core/utils/feature/build.gradle.kts
  core/utils/feature/src/main/AndroidManifest.xml
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/amplitude/AconAmplitude.kt
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/amplitude/AconTestAmplitude.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/acon/acon/data/dto/response/LoginResponse.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/model/user/VerificationStatus.kt
  feature/signin/build.gradle.kts
  feature/signin/src/main/AndroidManifest.xml
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInAmplitude.kt
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInScreen.kt
  feature/spot/build.gradle.kts
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  gradle/libs.versions.toml
Labels: 🐸성민🐸, INIT

#37 [Feat/#34] Amplitude 코드 추가
  app/src/main/java/com/acon/acon/amplitude/BottomAmplitude.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  core/utils/feature/build.gradle.kts
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/amplitude/AconAmplitude.kt
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/amplitude/AconTestAmplitude.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/repository/UserRepository.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/amplitude/ProfileAmplitude.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/amplitude/SettingsAmplitude.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/amplitude/DeleteAccountAmplitude.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/composable/DeleteAccountScreen.kt
  feature/signin/build.gradle.kts
  feature/signin/src/main/AndroidManifest.xml
  feature/signin/src/main/java/com/acon/acon/feature/signin/amplitude/SignInAmplitude.kt
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInScreen.kt
  feature/spot/build.gradle.kts
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotdetail/amplitude/SpotDetailAmplitude.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreen.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/amplitude/SpotListAmplitude.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/UploadContainer.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/amplitude/UploadAmplitude.kt
Labels: FEATURE✨, 🐸성민🐸

#38 [Mod/# 26] 앱 아이콘 이미지 변경
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: MOD✅, 🐸성민🐸

#40 [Fix] 1차 QA 버그 픽스
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/PreferenceMapScreen.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/component/DottoriSelectionBottomSheet.kt
  feature/areaverification/src/main/res/values/strings.xml
  feature/settings/src/main/java/com/acon/acon/feature/settings/component/SettingSectionItem.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/component/SettingSectionVersionItem.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/component/DeleteAccountTextField.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/composable/DeleteAccountScreen.kt
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/EmptySpotListView.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/bottomsheet/SpotFilterBottomSheet.kt
  feature/spot/src/main/res/values/strings.xml
  feature/upload/src/main/java/com/acon/acon/feature/upload/UploadSuccessContainer.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/component/LocationSearchBottomSheet.kt
Labels: HOTFIX🚨, FIX🔨, 🐸성민🐸
