Repository AconInc/ACON-Android, pull requests merged in 2025-03, with the labels that each got.

#42 [Fix] 1차 QA 수정사항
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
Labels: FIX🔨, 🐸성민🐸, UI✨

#44 [Fix/#43] onboarding gps bug fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  app/src/main/res/drawable/aconlogo.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/launch_background.xml
  app/src/main/res/values-v31/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/textfield/AconTextField.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/component/FoodGrid.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/component/FreqPlaceSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/component/OnboardingTopBar.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/component/PreferFoodTypeSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/component/PreferPlaceTypeSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/screen/OnboardingScreen/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/screen/OnboardingScreen/composable/OnboardingContainer.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/screen/OnboardingScreen/composable/OnboardingScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
  feature/profile/src/main/res/drawable/and_ic_progress_w_28.xml
Labels: FIX🔨, 🐇지원🐇

#48 [Hotfix/#47] release aab
  .github/workflows/android_build_ci.yml
  app/build.gradle.kts
  app/keystore/keystore_base64.txt
  app/proguard-rules.pro
  data/src/main/kotlin/com/acon/acon/data/repository/UserRepositoryImpl.kt
  gradle/libs.versions.toml
Labels: HOTFIX🚨, 🐸성민🐸

#50 [Fix/#49] 3차 QA Fix
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/AndroidManifest.xml
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationState.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationViewModel.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/PreferenceMapScreen.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/component/AreaVerificationBottomSheet.kt
  feature/areaverification/src/main/res/values/strings.xml
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/component/FoodGrid.kt
  feature/upload/src/main/java/com/acon/acon/feature/upload/UploadContainer.kt
Labels: FIX🔨, 🐸성민🐸

#52 [HotFix/#51] 비공개 테스트 1차 업데이트
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/bottomsheet/LoginBottomSheet.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/textfield/AconTextField.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/screen/OnboardingAmplitude.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/ProfilePhotoBox.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/ProfileTextField.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/component/DeleteAccountBottomSheet.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/bottomsheet/SpotFilterBottomSheet.kt
Labels: HOTFIX🚨, 🐸성민🐸
