Repository AconInc/ACON-Android, pull requests merged in 2025-04, with the labels that each got.

#59 [Refactor/#55] 코드 리팩토링
  .gitignore
  .idea/appInsightsSettings.xml
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/di/CoroutineDispatchersModule.kt
  app/src/main/java/com/acon/acon/di/CoroutineScopesModule.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SpotNavigation.kt
  core/common/src/main/java/com/acon/acon/core/common/DispatcherQualifiers.kt
  core/common/src/main/java/com/acon/acon/core/common/MyClass.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/component/dialog/PermissionDialog.kt
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/base/BaseContainerHost.kt
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/permission/LocationPermission.kt
  data/src/main/kotlin/com/acon/acon/data/SessionManager.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/local/TokenLocalDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/SpotRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/TokenRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/UserRemoteDataSource.kt
  data/src/main/kotlin/com/acon/acon/data/di/ApiModule.kt
  data/src/main/kotlin/com/acon/acon/data/di/AuthAuthenticator.kt
  data/src/main/kotlin/com/acon/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/acon/data/remote/SpotAuthApi.kt
  data/src/main/kotlin/com/acon/acon/data/remote/SpotNoAuthApi.kt
  data/src/main/kotlin/com/acon/acon/data/remote/UploadApi.kt
  data/src/main/kotlin/com/acon/acon/data/repository/OnboardingRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/SocialRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/TokenRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UploadRepositoryImpl.kt
  data/src/main/kotlin/com/acon/acon/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/acon/acon/domain/error/area/GetLegalDongError.kt
  domain/src/main/java/com/acon/acon/domain/error/upload/UploadReviewError.kt
  domain/src/main/java/com/acon/acon/domain/repository/SocialRepository.kt
  domain/src/main/java/com/acon/acon/domain/repository/TokenRepository.kt
  domain/src/main/java/com/acon/acon/domain/repository/UserRepository.kt
  domain/src/main/java/com/acon/acon/domain/type/UserType.kt
  feature/areaverification/build.gradle.kts
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationScreenContainer.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/SettingsViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreenContainer.kt
  feature/settings/src/main/java/com/acon/acon/feature/withdraw/screen/DeleteAccountViewModel.kt
  feature/signin/src/main/java/com/acon/acon/feature/signin/screen/SignInViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreenContainer.kt
Labels: REFACTOR🔃

#67 [Hotfix/#66] FlowRow 런타임 에러 해결
  gradle/libs.versions.toml
Labels: HOTFIX🚨

#61 [Fix#60] 비공개 테스트 4차 업데이트
  domain/src/main/java/com/acon/acon/domain/model/spot/SpotListRequest.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/ProfilePhotoBox.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/state/ConditionState.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/type/AvailableWalkingTimeType.kt
  feature/spot/src/main/java/com/acon/acon/feature/spot/type/RestaurantPriceRangeType.kt
  gradle/libs.versions.toml
Labels: FIX🔨

#65 [Feat/#64] 파이어베이스 CD 내용 수정
  .github/workflows/debug_build_ci.yml
  .github/workflows/firebase_cd.yml
Labels: FEATURE✨

#69 [Feat/#68] 디버그/릴리즈 앱 분리
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: FEATURE✨

#63 [Feat/#57] Firebase Crashlytics 연동
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/FirebaseConventionPlugin.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: FEATURE✨

#76 [Feat/#75] Acon 2.0 색상, 타이포 추가
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/acon/acon/core/designsystem/theme/Type.kt
Labels: FEATURE✨

#72 [Feat/#71] Timber 추가
  app/src/main/java/com/acon/acon/MainActivity.kt
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  data/src/main/kotlin/com/acon/acon/data/di/AuthAuthenticator.kt
  feature/areaverification/src/main/java/com/acon/acon/feature/areaverification/AreaVerificationViewModel.kt
  feature/onboarding/src/main/java/com/acon/acon/feature/onboarding/screen/PrefResultLoadingScreen/PrefResultLoadingScreenViewModel.kt
  gradle/libs.versions.toml
Labels: FEATURE✨

#83 [Refactor/#82] 예외 처리 내부 구조 변경
  core/common/src/main/java/com/acon/acon/core/common/AuthQualifiers.kt
  data/src/main/kotlin/com/acon/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/acon/data/error/ErrorCallAdapter.kt
  data/src/main/kotlin/com/acon/acon/data/error/ErrorUtils.kt
  data/src/main/kotlin/com/acon/acon/data/error/RemoteError.kt
Labels: REFACTOR🔃

#79 [Fix/#77] 프로필 버그 수정
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  core/utils/feature/src/main/java/com/acon/acon/core/utils/feature/toast/showToast.kt
  data/src/main/kotlin/com/acon/acon/data/datasource/remote/TokenRemoteDataSource.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/component/ProfilePhotoBox.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreenContainer.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/SettingsViewModel.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreen.kt
  feature/settings/src/main/java/com/acon/acon/feature/settings/screen/composable/SettingsScreenContainer.kt
Labels: FIX🔨, 성민

#81 [Fix/#78] 프로필 수정 갤러리 이미지 적용 개선
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/ProfileRoute.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/galleryGrid/GalleryGridViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/galleryGrid/composable/GalleryGridScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profile/composable/ProfileScreenContainer.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/ProfileModViewModel.kt
  feature/profile/src/main/java/com/acon/acon/feature/profile/composable/screen/profileMod/composable/ProfileModScreen.kt
Labels: FIX🔨, 성민
